### ISSUE TITLE
Waiting for the code and paper

### ISSUE THREAD

**Issue by CaptainEven** [LeiJ-USTB/MAF-Stereo#1]

**Comment by CaptainEven** [comment]
I nocticed the code already released, by the way is there a arxiv link?

**Comment by LeiJ-USTB** [comment]
Sorry, we have no plans to publish in arxiv, and will update the article link once the article is officially published.

**Comment by CaptainEven** [comment]
> Sorry, we have no plans to publish in arxiv, and will update the article link once the article is officially published.

got it
